theme: jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - resume.md 

style: light

markdown: GFM
url: 'https://dutchhagelslag.github.io/' # your main domain
baseurl: 'patricklee/' # if you're using custom domain keep this blank example: baseurl: ''

#markdown: kramdown
remote_theme: dutchhagelslag/jekyll-theme-console
