theme: jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - resume.md 

style: light

markdown: GFM
url: 'https://dutchhagelslag.github.io/' # your main domain
#baseurl: 'PythonFunctionLibrary/' # if you're using custom domain keep this blank example: baseurl: ''

#markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
